### ISSUE TITLE
need help from @Thrameos

### ISSUE THREAD

**Issue by mjsky481** [jpype-project/jpype#1229] opened 2024-11-05 08:02 UTC
@Thrameos Please help here. I posted the issue https://github.com/jpype-project/jpype/issues/1227 on the arm support here. However, it was closed brutally and disrespectfully by someone. Same for https://github.com/jpype-project/jpype/issues/1228

I don't think the issue is fixed and still see people asking for it or experiencing the same issue.
For example,
https://github.com/jpype-project/jpype/discussions/1203
https://github.com/jpype-project/jpype/issues/1227#issuecomment-2446429093
https://github.com/jpype-project/jpype/issues/1215
https://github.com/jpype-project/jpype/issues/1119

The doc said it should support aarch64 since 1.2.1 but the later releases didn't.
![image](https://github.com/user-attachments/assets/0caf1f6b-6243-495a-80f4-1a42d37b736e)

Hopefully the issue can be fixed soon. Thanks.

**Comment by Thrameos** [comment] 2024-11-05 12:02
Our releases are limited by the range of machines available on azure dev.  The comment in the log was for systems available at the time.  I am not sure if we were on azure or the previous cloud system which we had to abandon since.

I am not sure that there is currently an arm linux system in the image pool.  It may be possible to use cross compiler tools on azure but we don't have such a pattern.  You are always free to fork a copy and trigger dev builds using a free azure dev account (or am alternative github connected cloud) and getting the produced binaries or contributing build patterns to our release script.  If the architecture is not on azure, it may require a different cloud.

Openning a second issue is also not necessary.  You are always free to respond to a closed issue and the maintainer can reopen it.   Until I run the release scripts I won't have any idea what images we will be producing.    I don't have access the any machines for building images beyond the cloud so unless we have a build solution it won't happen.

 https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

**Comment by Thrameos** [comment] 2024-11-10 01:34
Closing this issue as the binaries for your system should be in anaconda framework.   I will try to see if the azure cloud provides the service, but if it does not that unfortunately you will need to go to find the anaconda build.   If it doesn't build there, the tag will be changed to "wontfix" as I don't have the time to build a new release pipeline ("it is what it is.").   You are free to set up an azure or other github connected cloud account on your branch and work on alternative release pipelines.   Whether it is included will depend on the maintainer.  I am the developer.

Though the issue is closed, you are free to comment.  (It doesn't matter if the issue is closed, I still get the email)
Please do not open another issue on this topic as arm builds have had multiple issues opened already.

**Closed by Thrameos** 2024-11-10 01:34 UTC
