### ISSUE TITLE
Is something wrong with the documentation website?

### ISSUE THREAD

**Issue by hx2A** [jpype-project/jpype#1060] opened 2022-05-04 11:19 UTC
Did something happen to the documentation website?

https://jpype.readthedocs.io/en/latest/

When I browse the documentation (which I do somewhat regularly) everything looks like a style sheet is missing or something. It's been like this for a while, and is very different from how it was a few months ago. Inspecting the webpages with browser developer tools does not turn up any 404 errors, so I can't tell if something is actually broken here.

If this is an intentional website change I apologize for opening this issue. I will say that the current documentation is much harder to read and find what I am looking for compared to how it was before. I like the previous version a lot better.

**Comment by Thrameos** [comment] 2022-05-04 12:15
It looks like there is a problem with the pages, but I am not aware of any changes that could be causing this.   I will investigate after I have finished working on glorious segfault.

**Comment by hx2A** [comment] 2022-05-04 12:23
Thank you for your hard work. The Glorious Segfault is obviously the priority. Good luck.

**Comment by Thrameos** [comment] 2022-05-14 16:14
@marscher  any insight on this issue?  I haven't messed with the doc stuff recently.

**Comment by Thrameos** [comment] 2022-05-14 16:26
I see one error in the build log, but could that actually be the issue.
https://readthedocs.org/projects/jpype/builds/16910920/

**Comment by marscher** [comment] 2022-05-14 16:40
Is there a way to clean the working/build directory? It seems like an incremental build, so this could break something eventually. Also the theme is not being used in any way.

**Comment by Thrameos** [comment] 2022-05-14 17:05
Not sure we have a specific pattern for cleaning the project.  I assumed that it was always pulled fresh on readthedocs.

``python setup.py clean`` looks like it only gets one architecture, not the docs, nor the test harness classes.   Perhaps we should enhance it to get other built files?

**Comment by marscher** [comment] 2022-05-14 17:39
I dont think its worth the effort implementing this. It runs a "git clean -ffd" so all the files generated in the working copy should be gone. 

I just built the docs locally, and the it just looks the same. I guess this is a theme error of some kind.

**Comment by Thrameos** [comment] 2022-05-15 13:38
I took another shot at this.   I checkout out previous releases and tried to build those locally.  Every pull I tried looks wrong in the same way.  This leaves two possiblities.

1) Is is not possible to build and display the docs locally.
2) We failed to pin the version for sphinx or readthedocs and thus something changed in the underlaying tools.

Given the way this problem occurred with no substantive changes in our doc files, I am going to assume the second is most likely.  Of course both could be true which would make debugging this issue a nightmare.   Not having something with a good start point makes this hard to debug.

Thus I will try pinning readthedocs to some old version and see if the built pages change.

**Comment by Thrameos** [comment] 2022-05-15 14:38
Still no dice, though I have an insight.  Using a very old copy of the website, I was able to diff and find out the issue is that currently built pages are missing "theme.css".  The css is in the build, it just isn't being included.    I just need to figure out what code is generating that section of the docs and trace back to the broken setting.

**Comment by Thrameos** [comment] 2022-05-15 15:16
Okay so the problem is the theme overrides.   It appears to be very fragile.  We want this content to be added to the page to deal with the table width, but it appears rather than being added it is flat out replacing the default.   I can get it to build properly locally, but something in the rtd scripts on their site is misinterpreting the directives.

**Comment by Thrameos** [comment] 2022-05-15 15:23
@marscher  I disabled the overrides for now as I have run out of development time for the day.   I am not sure quite how to proceed as debugging this will require fiddling with master until readthedocs is happy as I can't replicate it locally.   Should we leave this issue open or close it for now?

**Comment by hx2A** [comment] 2022-05-16 16:53
The documentation looks a lot better now. Thank you!

**Closed** 2022-05-16 17:20 UTC

**Comment by marscher** [comment] 2022-05-17 13:04
Thank a lot @Thrameos, I wasn't able to spend so much time on debugging. I would have expected a browser to complain about the missing theme.css file.

**Comment by Thrameos** [comment] 2022-05-18 13:20
Unfortunate it can't complain about something it does not know about.   The style sheet was right where is should be, it just wasn't included as there was some change in the behavior with sphinx.  I am not sure how the overrides are supposed to work where both the default and overrides get included.
