### ISSUE TITLE
ModuleNotFoundError: No module named 'jpype'

### ISSUE THREAD

**Issue by rakhmanu** [jpype-project/jpype#558] opened 2020-01-08 02:16 UTC
Hi,
I tried to install jpype by pip as follows

sudo pip3 install JPype1-py3

but, I received a bunch of errors; the screenshot is attached. Then I installed manually that package, and when I run, it says:  (the screenshot is also attached )
![jpype](https://user-images.githubusercontent.com/41294651/71944788-36e00680-3208-11ea-9eac-0b7186188861.png)
![jpype2](https://user-images.githubusercontent.com/41294651/71944797-40696e80-3208-11ea-87d0-01493e7557db.png)

 ModuleNotFoundError: No module named 'jpype'

If you have experienced this problem before, please give me any idea or recommendations to fix it
Thank you very much in advance

**Comment by Thrameos** [comment] 2020-01-08 04:43
You appear to not have python-devel package installed.   You will need the devel pacakge or install a wheel.  I will be posting wheel files shortly.

**Comment by rakhmanu** [comment] 2020-01-08 05:08
> You appear to not have python-devel package installed. You will need the devel pacakge or install a wheel. I will be posting wheel files shortly.

**Comment by rakhmanu** [comment] 2020-01-08 05:17
@Thrameos I got installed python-devel package, however it still does not work

**Comment by Thrameos** [comment] 2020-01-08 08:03
If the error is still Python.h is not found, then you likely have the incorrect python development package installed.  Also it appears that you are using a deprecated version.  JPype1-py3 is no longer supported.  Perhaps your system installed Python2-devel rather than Python3-devel?

**Comment by Thrameos** [comment] 2020-01-08 08:19
Please try with the wheel file attached to the release.

**Comment by Thrameos** [comment] 2020-01-08 14:35
Closing this one as the issue is about Jpype1-py3 which is a fork.

**Closed by Thrameos** 2020-01-08 14:35 UTC
