### ISSUE TITLE
import _jpype failed

### ISSUE THREAD

**Issue by liyu133** [jpype-project/jpype#905] opened 2020-12-05 02:50 UTC
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\python3.6.8\lib\site-packages\jpype\__init__.py", line 18, in <module>
    from ._jpackage import *
  File "D:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\python3.6.8\lib\site-packages\jpype\_jpackage.py", line 19, in <module>
    from . import _jclass
  File "D:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\python3.6.8\lib\site-packages\jpype\_jclass.py", line 17, in <module>
    import _jpype
  File "D:\pycharm\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: 找不到指定的模块。

**Comment by marscher** [comment] 2020-12-21 00:55
dumping stacktraces without any further information is not really helpful. I guess this is caused by the same root cause as the one for the issues importing on windows/python-3.9. So it should be fixed by #912

**Comment by Thrameos** [comment] 2020-12-21 02:04
Assuming this is 3.6.8 then this should be something else.   In 3.6.8 the GIL was held during LoadLibraryEx so the 3.9 bug is exclusively later versions.

My wife translates this as "Can't find the designated module." so it appears that _jpype module is not built or not on the search path.

**Comment by Thrameos** [comment] 2021-01-23 18:38
Closing due to lack of activity.

**Closed by Thrameos** 2021-01-23 18:38 UTC
