### ISSUE TITLE
segfault when slicing object array with nulls

### ISSUE THREAD

**Issue by adbull** [jpype-project/jpype#499] opened 2019-06-28 08:56 UTC
I get a segfault with the following code, on python 3.7.3, jpype 0.7.0, linux, installed with conda.

```python
>>> JArray(JObject)([None])[:]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdd2dc803de, pid=31815, tid=0x00007fdd4d4fc740
#
# JRE version: OpenJDK Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.201-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.cpython-37m-x86_64-linux-gnu.so+0x513de]  JPClass::getArrayRange(JPJavaFrame&, _jarray*, int, int)+0x7e

...

Process Python aborted (core dumped)
```

**Comment by Thrameos** [comment] 2019-06-28 14:51
Thanks for the bug report.  I will see where the source of the problem is coming from.  Just for clarification, what exactly is that line suppose to do?    It is supposed to be 

```  java
   Object[] values = new Object[]{null};
```

Thus values should an Object array length 1 with the element being a null pointer?

**Comment by adbull** [comment] 2019-06-28 15:32
Exactly, it creates a java array `new Object[]{null}`, which should then convert back to a python tuple `(None,)`.

**Comment by Thrameos** [comment] 2019-06-28 15:36
Okay, I think I can do that.  Thought I suspect it will produce tuple ``(JObject(None), )`` due to internal casting.  I am not sure how the smart the slice operator is with something like null pointers.  Of course that may be why it is crashing.

**Comment by Thrameos** [comment] 2019-06-28 21:09
Okay the problem has been fixed in a PR.  Not sure yet when we will have a maintenance release for 0.7.0 yet.

**Closed** 2019-06-29 04:05 UTC
Labels: bug
