### ISSUE TITLE
Daemon threads in Java preventing Python exit

### ISSUE THREAD

**Issue by pelson** [jpype-project/jpype#817] opened 2020-07-27 15:56 UTC
In ``JPype1<1.0`` user threads created in Java were being terminated early & abruptly if the main thread completed. Since ``JPype1 >= 1.0`` user threads are now honoured.

This seems like a very welcome improvement :+1:, but I didn't see this in the [changelog](https://jpype.readthedocs.io/en/latest/CHANGELOG.html). Was this intentional, and if so, should it be documented?

Code to emulate (excuse my poor Java):

```
package org.hello_world;


public class hello_world {
    public static void thread_hello() throws Exception {
        System.out.println("Setting up a thread");

        Thread t = new Thread(() -> {
            int count = 0;
            while (count < 10) {
                count++;
                try {
                    Thread.currentThread().sleep(1000);
                } catch (InterruptedException e) {
                }
            }
            System.out.println("Thread finished");
        });
        t.setDaemon(false);
        t.start();

        Thread.sleep(750);
        System.out.println("Done in the main thread");
    }
}
```

Which, after compiling with:

```
javac ./org/hello_world/hello_world.java
jar -c ./org/hello_world/hello_world.java ./org/hello_world/hello_world.class > hello-world.jar
```

And running with:

```
import pathlib

import jpype as jp


HERE = pathlib.Path(__file__).parent.absolute()


def test():
    jp.startJVM(f'-Djava.class.path={HERE}/hello-world.jar', convertStrings=False)
    cls = jp.JClass("org.hello_world.hello_world")
    cls.thread_hello()


if __name__ == '__main__':
    test()
```

Can be compared with both JPype 0.7.5 and JPype 1.0.1:

```
$ python -m pip list | grep -i jpype
JPype1                0.7.5               

$ time python run.py 
<java class 'org.hello_world.hello_world'>
Setting up a thread
Done in the main thread

real	0m1.090s
user	0m0.395s
sys	0m0.045s

```

```
$ python -m pip list | grep -i jpype
JPype1                1.0.1

$ time python run.py 
<java class 'org.hello_world.hello_world'>
Setting up a thread
Done in the main thread
Thread finished

real	0m10.428s
user	0m0.468s
sys	0m0.076s

```

Note: I found out about this through some convoluted static declaration in Java which was only hit in a few small cases in pytest tests. The symptom was that if I ran one of these special python tests (with the ``-k`` flag to pytest for instance), I was able to see that pytest ran everything as expected, even reporting the final results, but never actually terminated (so it just sat there without returning the prompt after running the tests). My first instinct was that this was another signal handler issue (e.g. #813) but couldn't find anything relevant in PyTest. As you can see, it turned out to be a complete red-herring, which I might not have fallen for with an relevant entry in the CHANGELOG. Hence the issue :wink:.

**Comment by Thrameos** [comment] 2020-07-27 16:34
Hmm. It appears that you are correct.   It had a big change log entry at some point, but somehow when was doing the merge of the log it appears that the entire entry got drop.  (There was one pull request that totally scrambled the log and I thought I merged everything in).  Big whoops, my apologies.

Starting in 0.7.4 the shutdown sequence was reworked extensively.   The final trigger to enable the shutdown changes was pulled in 1.0.  The old system did not actually call the JVM shutdown, but actually just called halt.  The side effect of calling shutdown was honoring user threads, calling atshutdown hooks, flushing buffers, closing files properly, and unfortunately freezes on bad code.  You can still do a halt if necessary to get the old behavior.  I will have to dig back through the archives and find the missing entry and make sure it reappears in the change log.

**Comment by michi42** [comment] 2020-07-27 19:23
Hi,

Thanks a lot for investigating this!
Unfortunately to me it looks like even daemon threads can block the JVM from exiting. Also, even calling `sys.exit()` explicitly does not terminate the JVM.

A mini example:
```
import jpype as jp
import sys

jp.startJVM()

Thread = jp.JClass("java.lang.Thread")
System = jp.JClass("java.lang.System")
tr = Thread(System.in_.read)
tr.setDaemon(True)
tr.start()

print(tr)
sys.exit(0)
```
Naively, I would expect the Java behavior:
- Since `tr` is a daemon thread, I would not expect that it blocks the JVM from exiting.
- I would expect that `sys.exit(0)` terminates the process, no matter what threads are still running.

**Comment by Thrameos** [comment] 2020-07-27 20:48
If you need to force stop the process use Runtime.halt() I believe.    

It should not prevent a shutdown on a daemon thread at least in the test cases I ran.   I will have to investigate that as a bug  but I am late getting the last patch release out, so I will have to do another later.

**Comment by michi42** [comment] 2020-07-28 14:03
Thanks for the quick feedback! And sure, do the patch release first.

Yes, `Runtime.halt()` should work, but it is kind of a big hammer and potentially leaves a mess behind.

What looks a bit confusing to me is that there seems to be no difference between the main/python thread finishing (in which case I fully agree the process should survive if there are some active non daemon Java threads), and any thread calling `exit()` (which should ideally be consistent with `System.exit()` in Java - i.e. allow to run finalization, but terminate all threads, including non daemon ones).

The "java equivalent" of the above example has this behavior:
```java
    public static void main(String[] args) throws Exception {
        Thread th = new Thread(() -> { try { System.in.read(); } catch (Exception e) { } });
        th.setDaemon(false);
        th.start();
        System.out.println("finishing main");
//        System.exit(0);
    }
```
Like this it will wait for the thread to finish; however if you un-comment `System.exit(0)`, it will terminate.

**Comment by pelson** [comment] 2020-07-29 08:39
The JNI docs seem to be fairly clear about the underlying [``jvm->DestroyJavaVM()``](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/invocation.html) call done in [JPype for shutdown](https://github.com/jpype-project/jpype/blob/v1.0.1/native/common/jp_context.cpp#L390):

> The JNI_DestroyJavaVM() function unloads a Java VM. As of JDK/JRE 1.1, only the main thread could unload the VM, by calling DestroyJavaVM. As of JDK/JRE 1.2, the restriction was removed, and any thread may call DestroyJavaVM to unload the VM.

> The VM waits until the current thread is the only non-daemon user thread before it actually unloads. User threads include both Java threads and attached native threads. This restriction exists because a Java thread or attached native thread may be holding system resources, such as locks, windows, and so on. The VM cannot automatically free these resources. By restricting the current thread to be the only running thread when the VM is unloaded, the burden of releasing system resources held by arbitrary threads is on the programmer.


I think there are actually three issues here:

 **1:** Changelog entry was missing. Fixed in #818. Thanks for that!

 **2:** daemon threads should not prevent JVM shutdown (called via the [``jpype._JTerminate`` ``atexit`` handler](https://github.com/jpype-project/jpype/blob/v1.0.1/jpype/_core.py#L326)). Code to reproduce (thanks Michi):

```
import jpype as jp

jp.startJVM()

Thread = jp.JClass("java.lang.Thread")
System = jp.JClass("java.lang.System")
tr = Thread(System.in_.read)
tr.setDaemon(True)
tr.start()

print("done - a daemon thread is running (awaiting stdin), but it shouldn't block immediate Python exit.")
```
In this case the ``atexit`` call to ``jpype._core.JTerminate`` *is* being called, but it doesn't result in termination of the program (i.e. **I think this is a bug**).

In contrast, Python does terminate with daemon threads (but not with non-daemon), as expected:

```
import sys, threading

def _thread():
    data = sys.stdin.readline()
    print("READ!", data)

thread = threading.Thread(target=_thread)
thread.daemon = True
thread.start()

print("Done! A daemon thread doesn't prevent Python exit")
```

 **3:** non-daemon user threads should not block ``sys.exit`` called from Python (even if ``Runtime.halt()`` has to be called by JPype to do it). (interpreted from @michi42's statement "I would expect that sys.exit(0) terminates the process, no matter what threads are still running.")

```
import jpype as jp
import sys


jp.startJVM()

Thread = jp.JClass("java.lang.Thread")
System = jp.JClass("java.lang.System")
tr = Thread(System.in_.read)
tr.setDaemon(False)
tr.start()

print("done - a non-daemon user thread is running (awaiting stdin), which will prevent immediate exit. Calling sys.exit should do the right thing though...")

sys.exit(0)
```

What actually happens is that the main thread is exited, but the non-daemon thread continues running.

It turns out that Python also has the expectation that non-daemonic threads should be appropriately terminated by the programmer (as is the case with Java). For example:

```
import atexit
import sys
import threading
import time


sys_exit_called = False


def _thread():
    while True:
        print("." if not sys_exit_called else "x", end="", flush=True)
        time.sleep(1)


thread = threading.Thread(target=_thread, daemon=False)
thread.start()

atexit.register(print, 'atexit triggered')


print("Done! A non-daemon thread does exit the main thread, but the other running thread continues until it is done")

sys_exit_called = True
sys.exit()
print('Never reached')
```

Results in the following output:

```
.Done! A non-daemon thread does exit the main thread, but the other running thread continues until it is done
xxxx
^CException ignored in: <module 'threading' from '/media/important/github/jpype/jpype/env_jkd11/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/media/important/github/jpype/jpype/env_jkd11/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
atexit triggered
```

So I'd conclude that the third issue is reasonable and consistent behaviour for both Java & Python, and isn't something that needs to be addressed (i.e. **I don't think this is a bug**).

**Comment by pelson** [comment] 2020-08-03 06:21
I renamed the issue, since I think the only thing remaining is the second issue ("daemon threads should not prevent JVM shutdown"). I was tempted to create another issue for it, but all of the history is in the thread that I wanted to keep close to the issue.

**Comment by Thrameos** [comment] 2020-08-03 14:25
I believe the title is incorrect.  I analyzed the test case and the issue is that an open JProxy call prevents shutdown.  As Python code has no way to get the exit call there is a reference counter in JProxy to make sure that we don't pull the rug out of on running Python code (which is a sure segmentation fault when it unwinds the stack).   

In this case, the daemon thread creates a Python lambda when the System.in_.read is added.  That lambda is holding the ref count at 1.  But because it a daemon thread is allowed to keep running it wont be informed about the exit.   When the cleanup routine reaches wait for stragglers stage, it sees a ref count on the proxy is 1, and will be deadlocked on a waiting daemon thread.  It can't yank the plug because if the proxy exits after the C++ resource is gone it is a segfault. 

About the only way I can prevent that would be for those proxies called from daemon threads to not count towards the open Proxy list.  But if that is the case then if something is frequently crossing the Python Java boundary on the daemon thread then we risk a segfault.   The problem here being that cleanup and atexit routine that are also alive at the exit time also need to be waited for as they are supposed be waited on.    If we cut off their resources then they will all fail too.  

(comment out line 72, 95 from JPypeProxy to try the alternative)

So the best way I see for this is to not actually delete the C++ resources until after the JVM shutdown is complete so that we don't get a race condition between the atexit threads and the context resource cleanup.   Instead we would have to queue up all the resource destruction and wait for  shutdown to complete.  In the case of this exit it doesn't mater as all the memory is going to die anyway.  In the case of a Python called shutdown we can execute the actual clean up routines when post shutdown routine is reached.  This solution requires adding a global handler list which is only used once exit is started.  All freeing of resources are directed to list rather than executed immediately.  The JVM completes it shutdown with all Python resources still in place.  We then yank the plug.   But the problem here is that the original code would still crash as we still have a stack frame on the zombie thread that winds through the deleted C++ items to deal with.

Yuck.  Never a good solution.

**Comment by Thrameos** [comment] 2020-08-04 03:53
Please test with #832 and see if it resolves the issues.

**Closed** 2020-08-20 09:28 UTC
Labels: bug
