### ISSUE TITLE
Glorious Segfault

### ISSUE THREAD

**Issue by astrelsky** [jpype-project/jpype#1050] opened 2022-04-17 23:27 UTC
Reproduction is fairly straightforward. I already took the liberty of finding the cause which I ended up doing with the Ghidra debugger. Having 3 separate debuggers for each language didn't suffice because it ended up being due to an exception from an exception being sent to python that was detected and causing a `JPypeException` to be thrown before going back to python and late enough in c++ to not know where it came from.

To reproduce simply create an interface such as the following and then attempt to import it in python.

```java
public interface BadInterface {
    public void __del__();
}
```

Here is what happens when it the type is created.

https://github.com/jpype-project/jpype/blob/0bacb9e57003f74aec05029caf58e1c707882b9c/native/python/pyjp_class.cpp#L1191-L1193

The `PyJPClass_Type->tp_new` there ends up calling `PyJPClass_new` which then gets up to this point which sets the Python exception and returns `NULL`.
https://github.com/jpype-project/jpype/blob/0bacb9e57003f74aec05029caf58e1c707882b9c/native/python/pyjp_class.cpp#L102-L107
 This then get's detected in the `JP_PY_CHECK` macro in `JPPyObject::call` which causes the `JPypeException` to be thrown. What happens from there I have no idea and probably shouldn't jump in without the necessary kevlar.

Hopefully this makes enough sense to hit the ground running at least.

**Comment by Thrameos** [comment] 2022-04-18 01:55
This may have aleeady been addressed. ( Looks familiar.)  Did you try with master?

**Comment by astrelsky** [comment] 2022-04-18 09:41
> This may have aleeady been addressed. ( Looks familiar.)  Did you try with master?

Yes

**Comment by Thrameos** [comment] 2022-04-23 16:48
Can you give some additional information on replication of this error?   I tried

```
import jpype
jpype.startJVM(classpath=".")
jpype.JClass("BadInterface")
```

and it gave me
```
Traceback (most recent call last):
  File "test5.py", line 4, in <module>
    jpype.JClass("BadInterface")
  File "/mnt/c/Users/nelson85/Documents/devel/open/jpype/jpype/_jclass.py", line 99, in __new__
    return _jpype._getClass(jc)
TypeError: finalizer conflict
```

which didn't match the reported symptoms because it wasn't a segfault.  My guess is that it did leave something in a bad state which lets to a later segfault, but not something replicable in my simple example.  I will try to identify what went wrong earlier in the process, but it would be good to be able to replicate the full bug to make sure it is addressed.  Will report when I make some progress.

**Comment by astrelsky** [comment] 2022-04-23 21:05
> Can you give some additional information on replication of this error?   I tried
> 
> ```
> import jpype
> jpype.startJVM(classpath=".")
> jpype.JClass("BadInterface")
> ```
> 
> and it gave me
> ```
> Traceback (most recent call last):
>   File "test5.py", line 4, in <module>
>     jpype.JClass("BadInterface")
>   File "/mnt/c/Users/nelson85/Documents/devel/open/jpype/jpype/_jclass.py", line 99, in __new__
>     return _jpype._getClass(jc)
> TypeError: finalizer conflict
> ```
> 
> which didn't match the reported symptoms because it wasn't a segfault.  My guess is that it did leave something in a bad state which lets to a later segfault, but not something replicable in my simple example.  I will try to identify what went wrong earlier in the process, but it would be good to be able to replicate the full bug to make sure it is addressed.  Will report when I make some progress.
> 
> 

`from package packagename import BadInterface`

**Comment by astrelsky** [comment] 2022-04-23 22:41
Here is a full example to reproduce.
[tmp.zip](https://github.com/jpype-project/jpype/files/8548745/tmp.zip)

**Comment by Thrameos** [comment] 2022-05-06 13:06
(Thanks for the code and sorry for the slow response,  Been stuck doing 65 to 80 hour works for a work demo, so no time for fun projects.)

I modified the example to 
```
import jpype
import jpype.imports

try:
    if __name__ == '__main__':
        jpype.startJVM(classpath=['tmp.jar'])
        from tmp import BadInterface
except Exception as ex:
    print("exception")

print("not segfault")
```

Version 1.3.0 windows:  exception, not segfault
Version 1.3.1 windows:  exception, not segfault
Version 1.3.0 linux:  exception, not segfault
Version 1.3.1 linux:  exception, not segfault

Thus all of the versions gave the same behavior.   Perhaps it is a different architecture?

There is no pattern which is producing a seg fault at least in this example when I tried each of the versions.   However, given that in all of them it is issuing an exception the issue is that it should have imported the bad class by ignoring the bad method name.    I will try to address that, but unless I can successfully replicate the segfault aspect I can't really address it.

**Comment by Thrameos** [comment] 2022-05-06 14:51
I am sorry but I have tried for hours and I can't replicate what you are seeing.   No path I have tried results in a segfault and I have other work that I have to attend to.   I am going forward with the release which this issue is holding up.  If you can replicate the issue again after the release please reopen the ticket as applying the dunder fix will close this.

**Comment by astrelsky** [comment] 2022-05-06 22:00
No problem. I'll try as hard as I can to break it again after the patch just to be sure and if I can't get it to crash it should be good enough for me.

It should have segfaulted immediately on import. If it doesn't for you then I'm wondering if it is jdk specific as I've replicated it on multiple machines. I'm using the latest eclipse temurin jdk 11

**Closed** 2022-05-09 16:10 UTC
