### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by EwoutH** [jpype-project/jpype#1147] opened 2023-09-26 11:25 UTC
[Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html) is releasing in [exactly one week](https://peps.python.org/pep-0693/), Monday 2023-10-02. It would be great if JPype could support Python 3.12 fully at the release, including testing in CI and wheels uploaded to PyPI.

<details><summary>Summary – Python 3.12 Release highlights</summary>

> New grammar features:
> - [PEP 701: Syntactic formalization of f-strings](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep701)
> 
> Interpreter improvements:
> - [PEP 684: A Per-Interpreter GIL](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep684)
> - [PEP 669: Low impact monitoring for CPython](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep669)
> 
> New typing features:
> - [PEP 688: Making the buffer protocol accessible in Python](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep688)
> -  [PEP 692: Using TypedDict for more precise **kwargs typing](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep692)
> -  [PEP 695: Type Parameter Syntax](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep695)
> - [PEP 698: Override Decorator for Static Typing](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep698)
> 
> Important deprecations, removals or restrictions:
> -  [PEP 623](https://peps.python.org/pep-0623/): Remove wstr from Unicode
> -  [PEP 632](https://peps.python.org/pep-0632/): Remove the distutils package. See [the migration guide](https://peps.python.org/pep-0632/#migration-advice) for advice on its replacement.
> -  [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/3.12/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/3.12/library/venv.html#venv-explanation) virtual environment.</details>

**Comment by marscher** [comment] 2023-09-28 04:40
Thanks. I'd welcome any PR fixing the issue with Python 3.12. Have a look at the details here: 

- https://github.com/conda-forge/jpype1-feedstock/pull/50/checks 

- https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=786512&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05&j=517fe804-fa30-5dc2-1413-330699242c05&t=c7d0fcb4-3a10-5b26-dfea-e879a93fc2ab

**Comment by Christopher-Chianelli** [comment] 2023-10-02 19:55
From the logs, it seems the issue is the change of location of ob_digit
```
  native/common/jp_primitivetype.cpp: In member function 'PyObject* JPPrimitiveType::convertLong(PyTypeObject*, PyLongObject*)':
  native/common/jp_primitivetype.cpp:50:25: error: 'PyLongObject' {aka 'struct _longobject'} has no member named 'ob_digit'
     50 |                 newobj->ob_digit[i] = tmp->ob_digit[i];
        |                         ^~~~~~~~
  native/common/jp_primitivetype.cpp:50:44: error: 'PyLongObject' {aka 'struct _longobject'} has no member named 'ob_digit'
     50 |                 newobj->ob_digit[i] = tmp->ob_digit[i];

```

According to https://github.com/cython/cython/issues/5238#issuecomment-1415089110 ; changing it to `((PyLongObject*)op1)->long_value->ob_digit` should work.

**Comment by Christopher-Chianelli** [comment] 2023-10-02 20:39
It more complicated than this, since wstr is now removed: https://www.python.org/dev/peps/pep-0623

**Comment by marscher** [comment] 2023-12-09 17:20
fixed by #1158

**Closed by marscher** 2023-12-09 17:20 UTC

**Comment by EwoutH** [comment] 2023-12-09 19:23
Awesome, thanks a lot!

When can we expect a release and wheels on n PyPI?

**Comment by Thrameos** [comment] 2023-12-10 18:56
Starting the process after fixing all merge requests.
