### ISSUE TITLE
Passing Parameters to the Execute Method in Cursor

### ISSUE THREAD

**Issue by ahmedpopal456** [jpype-project/jpype#291] opened 2018-03-10 00:17 UTC
When using Jaydebeapi to connect to a MSSQL Server Database, and call stored procedures. an error occurs, in specific cases. Check below

   
_wConnection = jaydebeapi.connect(jclassname=iClassName, url=iUrl, jars=iSSQLDriverPath, driver_args=iList)
cursor = wConnection.cursor()
      for item in df.collect():
cursor.execute("{call sp_UpsertTS(?,?,?,?,?,?)}", (item['id'], item['starttime'], item['endtime'], item['userid'], item['pairid'],item['username']))
wConnection.commit()
cursor.close()_

**Now, calling stored procedure like these works well with JayDeBeApi when the list of parameters I provide it with only contains strings. But the moment I provide a datetime, for example (like above), I get the following error:** 

No matching overloads found for setObject in find. at native/common/jp_method.cpp:127
Traceback (most recent call last):
  File "<stdin>", line 78, in main
  File "<stdin>", line 33, in importTS
  File "/mnt/resource/hadoop/yarn/local/usercache/livy/appcache/application_1520609118420_0015/spark-94797d6f-1bfa-4070-88fd-60e83922a44f/userFiles-60a55fd2-8bc1-4f85-89bc-4853fd6e06ab/sparksentinelcluster_dependencies_general.zip/jaydebeapi/__init__.py", line 499, in execute
    self._set_stmt_parms(self._prep, parameters)
  File "/mnt/resource/hadoop/yarn/local/usercache/livy/appcache/application_1520609118420_0015/spark-94797d6f-1bfa-4070-88fd-60e83922a44f/userFiles-60a55fd2-8bc1-4f85-89bc-4853fd6e06ab/sparksentinelcluster_dependencies_general.zip/jaydebeapi/__init__.py", line 490, in _set_stmt_parms
    prep_stmt.setObject(i + 1, parameters[i])
RuntimeError: No matching overloads found for setObject in find. at native/common/jp_method.cpp:127

**Comment by Thrameos** [comment] 2018-03-10 00:37
Can you use reflection on prep_stmt and see what are the overloads that are available?  If there is not an overload for DateTime then you will need to call a wrapper class to convert the datatime to match a specific overloaded type that setObject will handle.

**Comment by ahmedpopal456** [comment] 2018-03-10 03:04
hmmm, just did so,. It has an overload for DateTime , which does not count the nanosecond precision. The return from my query looks a little like this: 2018-03-09 16:35:41.730000 or even 2018-03-09 16:35:41.730000Z (int UTC).. which it does not support

**Comment by Thrameos** [comment] 2018-03-10 09:40
Not sure I understand.  Do you have a java or a python dateTime?  Unfortunately, the error message doesn't give the actual python type name of what was passed in.

**Comment by ausiddiqui** [comment] 2018-03-23 01:38
This same error occurs for pandas dataframe `datetime64[ns]` objects. The data stored in the pandas dataframe when printed as string would look like '2018-03-22 00:00:00'. 

I am inserting into Teradata table that I created which is expecting a 'TIMESTAMP' field type. 

Converting both the pandas dataframe field to python string / pandas object and the Teradata table to `VARCHAR` is the only way I am able to successfully run the `cursor.executemany()` statement.

**Comment by Thrameos** [comment] 2018-03-28 17:29
Perhaps if you showed the signature of the method including all the overloads and the types of each of the arguments I could help.  The type system tries to match the arguments against each overload by assigning each argument to either "exact", "implicit","explicit", or "none".   You can force an "exact" by creating a wrapper with the exact type of each of the arguments.   Usually if the match is ambiguous it will issue an error.  Though I suspect that this is an array or varargs interface so it is just guessing.  You also have the option of creating customizers for classes.  What is not clear is what overload and thus which particular conversions took place.  I suspect that it matched to a string which you would have to customize the str() command to get what you are looking for.  We do not have the ability to specify variable behavior for customization.   

Unfortunately, without knowing the exact types and the method signatures that are being matched, I do not think I can help further.

**Comment by ausiddiqui** [comment] 2018-03-28 20:52
Thanks for the response, not sure how to get you the "overloads", I used `pdb` and there wasn't anyway to inspect the variables in jaydebeapi, it was just a binary object and it fails at the point where a Python datetime field is being inserted as part of the prepared statement. If you look at the referenced issue on jaydebeapi I wrote down everything I tried and the way I called it with sample data as well. If you have an example of catching / inspecting the "overloads" for a related or unrelated issue I can try to implement that and give you the output. But I'm not sure where I would supply an argument to be exact/implicit/explicit/none, JPype is being used by Jaydebeapi and so it much further downstream from my code -- so it would likely result in re-writing the way Jaydebeapi is calling JPype is my lay man's understanding. 

What I am passing is at the most simplest level is a list of lists, such as: [['Chicago',1,'2018-03-23']] or 
[['Chicago',1,datetime.date(2018, 3, 23)]]. It is on the date variable that my errors are occurring, not to hijack the OP's post, but I believe our issues are one and the same or at least very closely related.

**Comment by Thrameos** [comment] 2018-03-28 21:53
I am guessing the problem is "cursor.execute(blah, blah)".   What I need to see is the overloads of execute  and the types of all the arguments.  There must be some kind of conversion process in which the python type object is being cast to a java object.   It may be something simple like datetime.date inherits from "str" thus we are creating a cast that should not have worked without a cast operation.  

Let me give you an example.  Suppose I was unable to get a command to execute properly. 
```
>>> from java.lang import String
>>> s=String.format(a,b,c)
Traceback (most recent call last):

  File "<ipython-input-27-a4fe58e0923b>", line 1, in <module>
    String.format(a,b,c)

RuntimeError: No matching overloads found for format in find. at native\common\jp_method.cpp:127
```

So I clearly am not getting the function that I expected so first I need to check to see what the overloads are for the class with that name.
```
>>> [ str(i) for i in String.class_.getDeclaredMethods() if i.getName()=='format']
['public static java.lang.String java.lang.String.format(java.util.Locale,java.lang.String,java.lang.Object[])',
 'public static java.lang.String java.lang.String.format(java.lang.String,java.lang.Object[])']
```

Okay so it is expecting either a string and a set of things that convert to objects, or a locale.  So next I need to see what is the types that I am feeding to the call.
```
>>> [ type(i) for i in (a,b,c)]
[int, str, NoneType]
```
Ah there is the problem.  An int can't match a java.lang.String or a java.util.Locale.  "str" type can cast to java.lang.Object, and NoneType can also match java.lang.Object.  Thus I need to add a conversion to make the first argument match.

But let's assume that you just see pkg.DateTime.  We don't have any inherent implied conversion, so it would have to be coming from a base class. Then we would need to see the list of base classes that pkg.DateTime is implementing.  It should be something like this...
```
>>> import inspect
>>> inspect.getmro(String)
(jpype._jclass.java.lang.String,
 jpype._jclass.java.lang.Comparable,
 jpype._jclass.java.io.Serializable,
 jpype._jclass.java.lang.Object,
 jpype._jclass.java.lang.CharSequence,
 jpype._jclass._JavaObject,
 object)
```

Thus I can see from this that I can use a String to hit any of those overloads. 

Without that sort of information, I can't really see what exactly is being called.  If it is something that you can't get to as a user then it is likely better on the Jaydebeapi forum, because I don't know anything about their internal structure.

**Comment by Thrameos** [comment] 2018-04-03 18:26
Has this issue been resolved?

**Comment by Thrameos** [comment] 2018-07-30 15:50
Closing request due to lack of user feedback.

**Closed by Thrameos** 2018-07-30 15:50 UTC
Labels: on-hold

**Comment by VivekUday26** [comment] 2020-04-20 04:44
This issue exisits for non datetime fields too. 
Here is my target DB - 
Content_ID - varchar(50)
Create_dt - Date FORMAT 'yyyy-mm-dd'
Flag NUMBER
Another_field varchar(50)

I eliminated one by one to know which column is throwing the error, it was the flag column. I have tried changing the data type to Float, Int, Byteint. Nothing works.

**Comment by Thrameos** [comment] 2020-04-20 15:37
Unfortunately your bug report is insufficient to reproduce.  I don't know enough about SQL and nothing in the report gives a way to replicate it.  Please send a report with a short snippet of code that replicates what you are seeing.   A simple github project which contains the jars you are using and contains a script that creates a database and tries to execute the offending command.
