### ISSUE TITLE
ReadTheDocs does not allow access to compiled code

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#488] opened 2019-06-24 17:07 UTC
In the javadoc PR I oversaw that you are importing _jpype, jpype as well as java bindings in the documentation. We can not do that on RTD. What is the exact purpose and can we somehow patch it?

**Comment by Thrameos** [comment] 2019-06-24 17:16
Locally I have been disabling the mock units on _jpype when building sphinx docs, but that is likely not an option on RTD.

I am guessing you are referring to the lines 
```
_jpype.setResource('GetClassMethod', _JClassNew)
_jpype.setResource('GetMethodDoc', _jmethodDoc)
```

These calls install the internal hooks to make ``__doc__`` and ``getClass`` work.  The ``getClass`` was on the initialize method, but it was actually misplaced as the install hooks all belong before anything is actually called.    

Not sure on the java binding reference... which line does that come in?

**Comment by Thrameos** [comment] 2019-06-24 17:18
As for a fix, I believe for the purposes of generating docs (so long as we don't want to generate docs from java), we can just mock the setResource call.  It is effectively just a stub if you are not live, and nothing will break so long as the JVM is not started.  Do the mock methods go in `doc/conf.py` for RTD?

**Comment by marscher** [comment] 2019-06-24 17:18
The imports you added to conf.py cause RTD to fail. You just added 
_jpype above the mocking. I will enable mocking only on RTD, to not 
hinder your development.

**Comment by Thrameos** [comment] 2019-06-24 17:22
It may be safe to pull ``_jpype`` from the ``conf.py``.  I don't recall which page failed to build without it.  I may have managed to bypass it.

**Comment by Thrameos** [comment] 2019-06-24 17:33
Okay finally replicated it.

``` 
$ python3 -m sphinx -b html doc doc/html
Running Sphinx v1.7.9

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\sphinx\config.py", line 161, in __init__
    execfile_(filename, config)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 66, in <module>
    import java.lang
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\imports.py", line 334, in create_module
    raise ImportError("Attempt to create java modules without jvm")
ImportError: Attempt to create java modules without jvm
```

I see it was for part of the API reference.  Let me see if I can patch it.

**Comment by marscher** [comment] 2019-06-24 17:36
I think we are not on the same page here. Your stack trace shows me that 
you are actually importing, accessing Java, right?

On readthedocs we are not allowed to compile anything, nor is there a 
JDK available. So we can either statically ship the java docs for a 
specific Java version (if we are legally allowed?) or just omit them.

**Comment by Thrameos** [comment] 2019-06-24 17:41
I think we are on the same page.  I just submitted a PR without the offending lines and am looking over the docs now to see what is busted.

It took me a while to get my system to be busted enough that it would fail like RTD.
```
nelson85@NELSON85PD2 ~/devel/open/jpype
$ python3 -m sphinx -b html doc doc/html
Running Sphinx v2.1.2
loading pickled environment... failed
failed: build environment version not current
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 9 source files that are out of date
updating environment: 9 added, 0 changed, 0 removed
reading sources... [100%] userguide
F:\nelson85pl\nelson85\devel\open\jpype\doc\install.rst:2: WARNING: Duplicate explicit target name: "anaconda".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] userguide
generating indices... genindex py-modindex
writing additional pages... searchC:\ProgramData\Miniconda3\lib\site-packages\sphinx_rtd_theme\search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}

copying images... [100%] attach_debugger.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in doc\html.
```

**Comment by Thrameos** [comment] 2019-06-24 17:45
The only things I see that is busted currently are the docs on the customizers.  I never managed to fix that one, so it is as intended.  Does RTD work with the PR now?

**Comment by marscher** [comment] 2019-06-24 17:46
That sounds great. RTD can only build branches in the repo, could you 
please push to origin?

**Comment by Thrameos** [comment] 2019-06-24 17:47
Assuming we are on the same page, I know what was going on.  I had a private page that was testing to see how the docstrings rendered.  It was never checked in but the changes required to get it to work (use of compiled objects) apparently did.   We don't need that functionality for RTD.

**Comment by Thrameos** [comment] 2019-06-24 17:49
Done.  Hope that fixes it.

**Closed** 2019-06-25 00:51 UTC
