### ISSUE TITLE
URLClassLoader doesn't work

### ISSUE THREAD

**Issue by lorandg** [jpype-project/jpype#177] opened 2016-03-04 13:43 UTC
**Following code doesn't work.**
import jpype
jpype.startJVM('/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so', '-ea')

jar1 = jpype.java.io.File("class1.jar") 

if jar1.exists():
    url1 = jar1.toURI().toURL()
    classloader1 = jpype.java.net.URLClassLoader([url1], jpype.java.lang.ClassLoader.getSystemClassLoader())

```
c1 = jpype.java.lang.Class.forName('test.Hello', True, classloader1)                   

newInstance1 = c1()
print "say "+ newInstance1.hello() 
```

else:
    print "jar not found"

**Returns:**
Traceback (most recent call last):
  File "/local/DD/lorandg/dev/jpype_classloader/classload.py", line 14, in <module>
    c1 = jpype.java.lang.Class.forName('test.Hello', True, classloader1)  
jpype._jexception.LinkageErrorPyRaisable: java.lang.NoClassDefFoundError: Ltest/Hello;

**Correspoding code in java work:**
         File myfile = new File("class1.jar")  ;

```
     if( myfile.exists())
     {
        URL url = myfile.toURI().toURL() ;
        URL[] array = {url} ;
        URLClassLoader classloader = new URLClassLoader(array ) ;

        Class c = Class.forName("test.Hello", true, classloader) ;  
        Method method = c.getMethod("hello");

        Object newInstance = c.newInstance();
        System.out.println("say "+ method.invoke(newInstance)) ;

        classloader.close();
     }
     else
     {
        System.out.println("jar not found") ;
     }
```

**Returns:**
say hello

**This is the java class in the class1.jar:**
package test;

public class Hello
{
   public String hello()
   {
      return "hello";
   }
}

**The python code works if I include class1.jar in classapth**
jpype.startJVM('/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so', '-ea', '-Djava.class.path=class1.jar')
But my goal is to load jar dynamically using URLClassLoader to implement a kind of plugins mechanism.

I use jpype on Debian wheezy with 
/usr/local/lib/python2.7/dist-packages/JPype1-0.6.1-py2.7-linux-x86_64.egg
and python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2

Thanks

**Comment by justussc** [comment] 2016-03-06 08:48
the problem is that jpype uses the FindClass jni call. that one in turn will use the systemclassloader. one work around is to replace the systemclassloader when you start the jvm. i don't know if that is an option for you, but a primitive solution would be

    package testloader;
    import java.net.URLClassLoader;
    import java.net.URL;

    public class MyClassLoader extends URLClassLoader {
        public MyClassLoader(ClassLoader parent) {
            super(new URL[0],parent);
        }
        public void addURL(URL url) {
            super.addURL(url);
        }
    }

and then start the jvm like

    jpype.startJVM(jpype.getDefaultJVMPath(),'-Djava.class.path=/path/to/testloader.jar', '-Djava.system.class.loader=testloader.MyClassLoader')
    # somehow get a new url
    systemclassloader = jpype.java.lang.ClassLoader.getSystemClassLoader()
    systemclassloader.addURL(url)
    jpype.JClass('someclassname.from.the.new.url')

**Comment by lorandg** [comment] 2016-03-08 10:13
Thank you.
It works fine when I try to load one Jars.
But in my case I would like to implement a plugin mechanism with jar containing same classes but in  different versions.

So in my test project I have got another jar with the same class but a different implementation. 

This is the java class in the class2.jar:
package test;

public class Hello
{
public String hello()
{
return "hello**2**";
}
}

Is there a way to wrap classloader mechanism in Jpype ?

Thank you.

**Comment by justussc** [comment] 2016-03-08 11:05
i am not a long time user of jpype, but as far as i could see there is one central cache from typename (string) to JPClass the c++ wrapper for a java class. so i don't think you can have multiple versions of the same class currently. but maybe others know better.

**Comment by Thrameos** [comment] 2018-07-30 15:45
That is the case.  This defect will be corrected in devel by using the java class pointer rather than the string name.  But this is still 6 months away.

**Comment by Thrameos** [comment] 2019-05-21 15:30
Fixed in 0.7 release.

**Closed by Thrameos** 2019-05-21 15:30 UTC
Labels: enhancement

**Comment by KOLANICH** [comment] 2019-05-21 17:46
Thank you.

**Comment by KOLANICH** [comment] 2019-08-05 12:51
tried setting classpath in runtime again, it doesn't work.
