### ISSUE TITLE
Amazon Corretto JVM

### ISSUE THREAD

**Issue by dhgary** [jpype-project/jpype#408] opened 2019-05-01 16:54 UTC
I would like to know if anyone has tried the Amazon Corretto JVM with jpype.  It crashes on startJVM.  I suspect it's not compatible with jpype, but would like to confirm.  Thank you.

>>> import jpype
>>> jpype.getDefaultJVMPath()
'C:\\Program Files (x86)\\Amazon Corretto\\jdk1.8.0_212\\jre\\bin\\server\\jvm.dll'

**Comment by Thrameos** [comment] 2019-05-01 17:46
I am not aware of anyone having tried with that jvm.  There is nothing inherent in jpype that should have a problem with alternative jvms so long as the jni layer has appropriate support.  However, it is also possible that we have some patterns that may not entirely conform the ordering assumptions of a particular jni as we mainly test on openJVM and oracleJVM.  Assuming it is just an order issue on the startup it may be possible to resolve by turning on tracing and finding which call is causing issues.

**Comment by dhgary** [comment] 2019-05-01 21:29
Thank you for your response.  I’m not sure what to think.  I’ve tried it on couple of different Windows machines now via the python interactive window.  When startJVM is triggered it hangs, process has to be killed.  So it never gets to the except.

>>> from jpype import *
>>> try:
...           startJVM(getDefaultJVMPath(), "-ea")
... except JavaException, ex:
...           if ex.javaClass() is java.lang.RuntimeException :
...                         print "Caught the runtime exception : ", ex.message()
...                         print ex.stacktrace()

Hanging was the most common result. Over a few hours, probably 90% of my tests hung.  About 9% of my test were an instant crash that killed the process.  And about 1% of the tests actually appeared to work.  Frustrated that I can’t get any kind of trace showing the problem.

**Comment by Thrameos** [comment] 2019-05-02 00:10
Just for clarity are you running the python trace routines or the jpype tracing methods?  In python tracer it will just tell you it died or froze in startJVM with no explaination.  With the jpype tracing it will print out each jvm call that was made so you can get down to the exact point of the failure assuming it is repeatable usually with a blizzard of error messages as a death or freeze in startJVM is usually caused by an exception being thrown before we have finished getting the java resources needed to reflect it back to python.   (There are untestable edge cases where such as JVM was started but the class table is not complete, etc.  Though I have tried to route those all to an exception or a segfault where I could.)

To trace with jpype, you must recompile with the TRACE switch uncommented  and run a test dumping the stdout to a log file.  The log will be pretty long but should show .  Last you may want to try with the devel version rather than release.  There was a major rewrite of the core to deal with structural problems.  Most of the major fixes were backported to keep release running, but not all.

**Comment by Thrameos** [comment] 2019-05-13 05:38
I tested both versions 8 and 11 on Window_x64.  Both run a simple test case without issue.  Are you sure that installation of Corretto is correct?

**Comment by dhgary** [comment] 2019-05-13 12:42
Thanks for your update.  Other than the two machines that failed initially, we’ve been able to run successfully.  I need to go back and look at those two machines when I have time.

**Comment by Thrameos** [comment] 2019-05-13 21:35
Okay I am going to close this request for now.  If you have more information on the fails, please reopen the thread.

**Closed by Thrameos** 2019-05-13 21:35 UTC
Labels: enhancement
