### ISSUE TITLE
startJVM should raise errors for invalid options.

### ISSUE THREAD

**Issue by spookylukey** [jpype-project/jpype#268] opened 2017-11-08 17:00 UTC
Example:

    >>> jpype.startJVM(jpype.getDefaultJVMPath(), "-rubbish")
    >>> java.lang.System.out.println("hello world")
    Hello world

I would expect this to raise an exception for '-rubbish', in the way that the 'java' and 'javac' commands do.

In addition, since '-classpath' option doesn't work (as documented under the incorrectly named `startupJVM` method), that option should also raise an exception. This, combined with issue #267, meant it has taken me 30 minutes to get started with jpype instead of 5, and very nearly gave up.

**Comment by marscher** [comment] 2017-11-09 15:57
classpath is working as expected. Can you please point us to the wrong part of the documentation then?
If you pass rubbish, what is the actual programs behaviour?

**Comment by Thrameos** [comment] 2017-12-01 01:12
The current behavior is to silently eat any options that are not accepted.   However, it appears in the code there is some undocumented options.  I see a flag called "ignoreUnrecognized" that seems like it is likely causing the issue.  I am not sure how to set the option as it appears to be coming from the line

```_jpype.startup(jvm, tuple(args), True)```

Changing the `True` to `False` gave me...

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    jpype.startJVM(jpype.getDefaultJVMPath(),'-rubbish')
  File "C:\cygwin64\home\nelson85\bitb\devel\contrib\jpype\jpype\_core.py", line 70, in startJVM
    _jpype.startup(jvm, tuple(args), False)
RuntimeError: Unable to start JVM at native\common\jp_env.cpp:78
Unrecognized option: -rubbish
```

I am not sure why we would want to eat arguments that aren't recognized by default other than we are forcing the user to hard code the path currently.  At minimum the option should be exposed as a keyword argument as `jpype.startJVM(getDefaultJVMPath(),'-rubbish`, ignore=True)' so that if rubbish is valid for some jvm it will allow it.

On that front it may be a good idea to just revise our start routine.  If we specify keyword arguments for startJVM, we would be sure that the users are specifying expected options.  We can add arguments for all of the common JVM options.  This may make it possible to make it more portable as if there is a difference between two different jvm arguments we could in principle detect the difference and change the option value rather that requiring hardcoding of the jvm options.  

`startJVM(getDefaultJVMPath(), classpath="myclasspath", )`

It could be backward compatible so it would not break existing code.

**Comment by Thrameos** [comment] 2017-12-01 01:13
I do not see anything to get a list of valid options from the jvm in https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/invocation.html.

**Comment by spookylukey** [comment] 2017-12-03 12:18
@marscher Regarding the `-classpath` option, the docs here claim that it doesn't work - http://jpype.readthedocs.io/en/latest/userguide.html#id41
and that is what I found in practice - you have to pass `-Djava.class.path=...` instead.

**Comment by Thrameos** [comment] 2017-12-04 17:20
So do we have any objections to changing ignoreUnrecognized from True to False.  

Points I see:
1) it will make `-classpath` return an error saving some new users.
2) it will break some existing code especially if someone is working with multiple jvm that have different options.

So long as we have a keywords arguments so we can do

`startJVM(getDefaultJVMPath(), ..., ignoreUnrecognized=True)` 

to get the previous behavior then I think that point 1 wins over point 2.

**Comment by marscher** [comment] 2017-12-04 17:21
I agree on this order. Failures should not be silent.

**Comment by Thrameos** [comment] 2017-12-04 17:46
Okay should be in pull #272

**Comment by marscher** [comment] 2017-12-04 17:53
cool. Thank you!

**Comment by Thrameos** [comment] 2017-12-04 18:26
Should we make classpath an optional argument?

`startJVM(getDefaultJVMPath(), classpath='C:\foo')`

It would still support the old form.   It would just make the most common option more clear.

**Comment by marscher** [comment] 2017-12-04 18:27
we could also transparently translate "classpath" to the -D form right?

**Comment by Thrameos** [comment] 2017-12-04 18:31
Correct.  It would just add the `-Dclasspath=C:\foo` to the arguments.   I know that python prefers to have one method of doing things and thus having sugar for the most common argument may not fit with the design philosophy.   But as this is one of the most common errors it seems like it may be better to be explicit.

**Comment by marscher** [comment] 2017-12-04 18:34
right. Explicit should actually raise in this case, but for the sake of
simple usage, I'd just translate it (eg. trigger a warning that this is
deprecated).

**Comment by Thrameos** [comment] 2017-12-04 18:35
Actually I misunderstood.   Would you rather make it automatically translate the argument

`startJVM(getDefaultJVMPath(), '-classpath=C:\Foo')` 

into

`startJVM(getDefaultJVMPath(), '-Dclasspath=C:\Foo')` 

by looking through the arguments or do you support having classpath as an explicit argument? Ie.

`startJVM(getDefaultJVMPath(), classpath='C:\Foo')`

**Comment by marscher** [comment] 2017-12-04 18:43
sorry I also misunderstood this. Adding an explicit classpath argument breaks the api, I think we should avoid this. However we can check internally, without breaking stuff, if a plain classpath argument has been given, trigger a warning and translate into the supported option.

So you got this right I guess 👍

**Comment by Thrameos** [comment] 2017-12-04 18:49
I don't think it breaks it.  

`startJVM(getDefaultJVMPath(), classpath='C:\Foo')`

```python
def startJVM(jvm, *args, ignoreUnrecognized=False, classpath=None):
         args=list(args)
         if classpath!=None:
            args.append('-Dclasspath=%s'%classpath)
         _jpype.startup(jvm, tuple(args), ignoreUnrecognized)
         ...
```

The other method also works but there are issues.   In java the expected arguments for classpath would be

`startJVM(getDefaultJVMPath(), '-classpath', 'C:\Foo')`

I am not sure we really want to support that.

From the java docs.
```
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -server       to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
```

**Comment by marscher** [comment] 2017-12-04 18:52
If we introduce this parameter and people already have a cp defined as a normal argument it gets overwritten by the new one. But since it is explicit this is actually expected behaviour, I like your solution.

**Comment by jbfaden** [comment] 2019-01-10 13:33
I'd like to get more involved with this group, but here's my outside perspective.  I have a Java code to which I need to provide access in Matlab and IDL, and because of jpype I can now offer this to scientists using Python/Numpy as well.  I've found that in Matlab, making my software available is trivial, in IDL it's a bit more difficult, and jpype is lacking.  In Matlab you can say:

javaaddpath( 'http://autoplot.org/jnlp/latest/autoplot.jar' )

and now "org" is defined, without any JPackage-type imports.  I'm experimenting with writing a similar code for jpype, but my python is a little lacking.  Here are the three pages which describe use in each environment:

http://autoplot.org/python
http://autoplot.org/matlab
http://autoplot.org/idl

**Comment by Thrameos** [comment] 2019-05-23 08:02
@jbfaden I attempted to address your wish to be able to pull the jar through http.  Unfortunately, no matter what I tried your jar would not pull through the standard URLClassLoader when it was an http,  It worked perfectly when it was on the local disk, but never when pulling through http.   Examining your jar file it is clear that your jar is too clever by half.  You have merged a shell script (not to mention a lot of non-java stuff inside the jar, but the loader doesn't care about that.)  Java unfortunately only supports jars that start with the standard ZIP header when loading from JarInputStream.  It works fine in JarFile which is used locally.  The Java JarInputStream does not have random access so it can't go looking through the file trying to find the header.  The Java URLLoader looks at the URL type and decides to load either through to open was a JarInputStream or a JarFile depending on whether the connection supports random access.

Also I am not quite sure that it would be a good idea to pull a 30M jar file each time a program is run.  It is clear what Matlab is doing is pulling the jar into a local cache directory some place and then opening it with JarFile which would skip the garbage at the front.   I did not see a good way to make the same thing happen without adding a good amount of custom code.  I looked through the java.net API and did not see a file based caching system that would be useful for this request.  Adding our own caching system just to support this small feature of saving the user from downloading prior to using seems a bit much.  But perhaps I missed something in the Java APIs that could help.

Assuming that I could get the jar pulled someplace that it was readable, it is a simple matter of getting a class loader on the file.  We would need to entend support to the jpype.imports api if a custom classloader was to be used for a portion of the import tree.   It seems like a reasonable lift, but as I can't get the your particular jar to unpack at all without downloading it, I am not sure there is much benefit to your particular configuration.

**Comment by Thrameos** [comment] 2019-06-25 14:58
The original request has been completed.  The secondary request was addressed, thus I am closing this thread.  If you have additional requests, please file a new ticket.

**Closed by Thrameos** 2019-06-25 14:58 UTC
Labels: enhancement

**Comment by jbfaden** [comment] 2019-06-26 11:31
@Thrameos thanks for looking into this.  What I did a while back was to write a routine which can be used as a helper outside of jpype, https://svn.code.sf.net/p/autoplot/code/autoplot/trunk/Autoplot/src/external/jpypeutil.py
which downloads to a cache file in /tmp, and will continue to use the cached jar if the size doesn't change.  And a Python-savy colleague set this up on pip, which is described at: https://github.com/autoplot/python/ .  It's been a couple of months since I've played with this, but this seems good enough if not ideal.

**Comment by Thrameos** [comment] 2019-06-26 16:54
Yeah that it about what it would take.  The standard URLClassloader available from within Java won't skip garbage at the front of a Jar the way the FileClassloader version does due to differences between the serial access and random access.  If I could find a general support for download and caching in Java then I can add it to JPype.  For now your solutions seems like the best.
