### ISSUE TITLE
Exceptions in customizers __jclass_init__ crash the JVM

### ISSUE THREAD

**Issue by astrelsky** [jpype-project/jpype#1198] opened 2024-06-27 18:08 UTC
Below is a silly example to reproduce the problem. I just picked a class at random that didn't have a customizer provided by jpype. There is no purpose for a customizer for this class other then demonstrating the issue.

```py
import jpype
from jpype.imports import *

jpype.startJVM()

@jpype.JImplementationFor("java.io.Console")
class Console:
    def __jclass_init__(self):
        raise Exception("hi")


from java.io import Console

```

The crash appears to be from an uncaught exception in `PyJPClass_hook` around (pyjp_class.cpp:1200)

**Comment by Thrameos** [comment] 2024-06-27 18:48
I did not get a crash on my machine.   Perhaps we need more details in terms of versions or arch....

```$ python3 test3.py
Traceback (most recent call last):
  File "test3.py", line 11, in <module>
    from java.io import Console
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
Exception: hi
```

**Comment by astrelsky** [comment] 2024-06-27 19:25
> I did not get a crash on my machine. Perhaps we need more details in terms of versions or arch....
> 
> ```
> Traceback (most recent call last):
>   File "test3.py", line 11, in <module>
>     from java.io import Console
>   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
> Exception: hi
> ```

Windows 10 and 11. JDK 21, 22 and JDK 8. Python 3.11.7, 3.12.1 and 3.8.10. I tried the lowest supported versions of Java and Python that had pre-built wheels for Jpype1 (to eliminate variables), that I could get my hands on.

**Comment by Thrameos** [comment] 2024-06-27 19:51
Got it.   Will try though I have a few other items in the queue already.

**Comment by Thrameos** [comment] 2024-06-27 21:49
I understand the issue.  The problem is to prevent name mangling we are declaring functions as ``extern "C"`` but also supplying ``/EHsc`` which means that they are not allowed to throw.   Because of this we end up with an exception which is going from C++ to C++ failing.   Either we have to remove all ``extern "C"``  declarations or switch to ``/EHa /EHs" when compiling.   

The problem was compounded because the ``extern "C"`` was in the header rather than definition.   Thus absolutely nothing appears wrong in the code.

**Comment by Thrameos** [comment] 2024-06-27 21:54
A PR with the fix is posted.   It will be included in the next release.   Though I haven't seen any responses from the maintainer in a while so not sure when it will get reviewed.

**Comment by astrelsky** [comment] 2024-06-28 09:02
> A PR with the fix is posted.   It will be included in the next release.   Though I haven't seen any responses from the maintainer in a while so not sure when it will get reviewed.

Nice that was quick. Thank you very much.

**Comment by Thrameos** [comment] 2024-06-28 13:57
It was a one liner.   So not that impressive.  The longer job would be verifying all of the other calls in module dont have the same problem.

**Comment by astrelsky** [comment] 2024-06-29 09:14
> It was a one liner. So not that impressive. The longer job would be verifying all of the other calls in module don't have the same problem.

I did take a quick look yesterday and I _think_ everything else is ok.

**Closed** 2024-08-19 21:48 UTC
