### ISSUE TITLE
Unresolvable ambiguous overload for booleans

### ISSUE THREAD

**Issue by ljeub-pometry** [jpype-project/jpype#1112] opened 2022-11-25 13:17 UTC
When writing wrappers for calling raphtory from python (see https://github.com/Raphtory/Raphtory/pull/704) we ran into an issue with ambiguous overloads for our methods that I was unable to resolve. 

I can reproduce the issue using three simple java classes:

```java
public class TestType {}
```

```java
public class TestTypeDerived extends TestType {}
```

```java
public class OverloadTest {
    public static void test(boolean a, TestType b) {
        String astr = Boolean.valueOf(a).toString();
        System.out.println("boolean called: " + astr);
    }

    public static  void test(Object a, TestType b) {
        System.out.println("object called: " + a.toString());
    }

    public static void main(String args[])
    {

        test(false, new TestTypeDerived());
        test("that", new TestTypeDerived());
    }
}
```

Calling this from java works as expected and outputs
```
boolean called: false
object called: that
```

However, if I try to call the `test` method from python using JPype the boolean case raises an ambiguous overload error when called with the derived type. Here is the python script I used to test this:

```python
import jpype.imports
from jpype import JClass, JBoolean, JObject
from pathlib import Path

path = [str(Path(__file__).parents[1] / "out/production/JPypeOverloadIssue")]  # set appropriately


if __name__ == "__main__":
    jpype.startJVM(classpath=path)
    from java.lang import Boolean, Object
    test = JClass("OverloadTest")
    test_type = JClass("TestType")()
    test_type_derived = JClass("TestTypeDerived")()
    test.test(True, test_type)  # works
    test.test("that", test_type)  # works
    test.test("that", test_type_derived)  # works
    test.test(JObject(True, Object), test_type_derived)  # works and calls object overload
    test.test(JObject(True, Boolean), test_type_derived)  # ambiguous overload
    test.test(True, test_type_derived)  # ambiguous overload
    test.test(JBoolean(True), test_type_derived)  # ambiguous overload
```

I would be willing to spend some time to try to fix this issue myself but I would need some pointers as to where to start.

**Comment by Thrameos** [comment] 2022-11-25 18:37
The issue is in the method resolution.   Current JPype uses a simple scheme for resolution when there is no governing rules provided by the Java method overloading.   There is a 4 level resolution for each match (exact, implicit, explicit, and none).  It goes through each overload and gets the matching of each.   Each match is given the lowest overload match.   If two are at the same match level then it decides that is ambiguous. 

In this case the "test_type_derived" is forcing the match to implicit so therefore it can't decide if bool or object match regardless of whether the cast is applied or not.  It is true that (exact, implicit) should be better than (implicit, implicit) but we don't have that level of sophistication.   The underlaying issue is that derived should be like exact, but isn't so that we can resolve the cases where multiple inherited objects are used for the overload.  

Oddly if you test Java directly the case ```test.test(new java.lang.Boolean(false), test_type_derived)`` will go to ``object``.

The current resolution would be to cast the second argument which ups its match to exact.
```
     TestType = jpype.JClass("TestType")
     test.test(True, TestType @ test_type_derived)  # ambiguous overload, resolved by cast
     test.test(JBoolean(True), TestType @ test_type_derived)  # ambiguous overload, resolved by cast
```

There are two methods that we use to resolve this but they are rather crude.  One is written in C and the other is in Java.   Then it probes for a method the first time in Java there is code that generates the list of which overloads mask others.   That is supposed to resolve this by saying ``test.test(bool, TestType)`` masks ``test.test(Object,TestType)``.  But it were to do so then ``test.test(java.lang.Boolean, TestType)`` would go to ``test.test(bool, TestType)`` which doesn't match the Java language.  The C method is the 4 types we discussed earlier.   I have debated for a long type whether there should be a 5th level of derived which is better than implicit.

So lets see if adding a 5th level resolves this problem....

``test.test(JBoolean(True), test_type_derived)`` 
 -  matches ``test.test(bool, TestType)`` with (exact,derived) => derived    
 -  matches ``test.test(Object, TestType)`` with (implicit,derived) => implicit

So it is unambiguously better to go to the first.    

Next.

``test.test(java.lang.Boolean(True), test_type_derived)`` 
 -  matches ``test.test(bool, TestType)`` with (implicit,derived) => implicit    
 -  matches ``test.test(Object, TestType)`` with (derived,derived) => derived
So it is unambiguously better to go to the second.    

Conclusion, it is fixable with a change to the C API.   

technical details
------------------
The enum types are located in ``common/native/include/jp_match.h``  so we can add a new level between ``_implicit`` and ``_exact```.

The conversion rules are located in ``common/native/jp_classhints.cpp`` in ``JPConversionObject``

```
        virtual JPMatch::Type matches(JPClass *cls, JPMatch &match) override
        {
                JP_TRACE_IN("JPConversionObject::matches");
                JPValue *value = match.getJavaSlot();
                if (value == NULL || match.frame == NULL)
                        return match.type = JPMatch::_none;
                match.conversion = this;
                JPClass *oc = value->getClass();
                if (oc == NULL)
                        return match.type = JPMatch::_none;
                if (oc == cls)
                {
                        // hey, this is me! :)
                        return match.type = JPMatch::_exact;
                }
                bool assignable = match.frame->IsAssignableFrom(oc->getJavaClass(), cls->getJavaClass()) != 0;
                JP_TRACE("assignable", assignable, oc->getCanonicalName(), cls->getCanonicalName());
                match.type = (assignable ? JPMatch::_implicit : JPMatch::_none);  // <== here would need to use the new level

                // This is the one except to the conversion rule patterns.
                // If it is a Java value then we must prevent it from proceeding
                // through the conversion rules even if it was not a match.
                // Thus the return result and the match type differ here.
                return JPMatch::_implicit;
                JP_TRACE_OUT;
        }
```

Next up is the audit information which is supposed to be able to report the quality of the match to a user which would need to know about the new level.  That would be ``PyJPClass_canConvertToJava`` in ``native/python/pyjp_class.cpp``.

And last would be the documentation section under ``Java conversions`` is ``doc/userguide.rst``.

We would not need to touch the Java overload list.   For reference it is in ``native/java/org/jpype/manager/MethodOverload.java``.

@marscher It would be good to get your input on this one.   I can fix it with about a ~5 line change by adding a new level to the enum table, changing the object conversion to use, and then updating the auditing logic so that it reports the new level of matching, but I am somewhat worried that this would be a major change in the resolution policy.   It should in principle never make something ambiguous that wasn't before but it is hard for me to see all of the possible interplay that it could have.   The whole logic of method resolution predates me (though I rewrote it to be easier to maintain), I haven't ever changed its rules.  The current rules are as I see it "exact always wins", "use Java overloading list otherwise", else "report ambiguity".  This would add a new dimension to the third case.   It is also unclear if it should be before or after the second rule.

**Comment by Thrameos** [comment] 2022-11-29 17:42
My guess is that if the new rule is the last rule before reporting an ambiguity then it can only resolve an ambiguity and never change an existing resolution as the only outcome that it avoids is error reporting.   If we place it any higher on the list then it could change which method is resolved which we must avoid.  The test cases here can be added to the test bench, but it is hard to think of test cases that would actually prove that every resolution for each number of arguments will work.   To properly test it we would have to hit every combination of [primitives(including all promotions), boxed, string, specific object instance, derived object instance] for 1 to 3 arguments plus variadic methods.   That would be an very large matrix.

**Comment by Thrameos** [comment] 2022-11-30 05:53
@ljeub-pometry I put in a PR to resolve this issue.  You can test it to see if it fixes your problem.   It may take a while to update the test bench before we can include this as changes to the method resolution process have to be thoroughly tested.

**Comment by marscher** [comment] 2022-12-09 12:17
> to properly test it we would have to hit every combination of [primitives(including all promotions), boxed, string, specific object instance, derived object instance] for 1 to 3 arguments plus variadic methods. That would be an very large matrix.

I think this is what pytest.parameterize is suited for https://docs.pytest.org/en/latest/example/parametrize.html
The problem would be to compute, when an ambiguity is reported.

But I think you made this very clear. Since it is the last rule in the chain, it should not change the existing behaviour. So actually your added tests are sufficient IMO.

**Comment by Thrameos** [comment] 2022-12-09 16:58
Sounds good.  Lets target this for a review then.   I assume that this should bump the minor number to 1.5?

**Comment by marscher** [comment] 2022-12-10 20:35
Yes, that is a change demanding for a minor release.

**Comment by ljeub-pometry** [comment] 2022-12-12 11:09
> @ljeub-pometry I put in a PR to resolve this issue. You can test it to see if it fixes your problem. It may take a while to update the test bench before we can include this as changes to the method resolution process have to be thoroughly tested.

I can confirm that #1113 indeed solves the issue we were having in Raphtory. If there is anything we can do to help move this along, let me know!

**Closed** 2023-04-04 00:21 UTC
Labels: enhancement
