### ISSUE TITLE
Ambiguous overloads found

### ISSUE THREAD

**Issue by knabbers** [jpype-project/jpype#344] opened 2018-09-17 15:10 UTC
I don't think JPype correctly resolves variadic function overloads properly.
An example:
```
class Foo{
    public Foo(){} // (separate issue: doesn't work without this - I would've thought it should..?)

    public void bar(int x, String... ss){
        System.out.println("varargs");
    }

    public void bar(int x){
        System.out.println("noargs");
    }

    public static void main(String[] args){
        new Foo().bar(1);
    }
}
```
Then compile it and run:
```
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())

foo = jpype.JClass('Foo')
print("Java says:")
foo.main([])
print("..but JPype errors:")
foo().bar(1)

jpype.shutdownJVM()
```
Output is 
stdout:
```
Java says:
noargs
..but JPype errors:
```
stderr:
```
Traceback (most recent call last):
  File "/home/mboughe/Desktop/jpypetest/issue.py", line 8, in <module>
    foo().bar(1)
  File "/home/matt/anaconda3/envs/py27/lib/python2.7/site-packages/jpype/_jclass.py", line 111, in _javaInit
    *args)
RuntimeError: No matching overloads found for [init in find. at native/common/jp_method.cpp:127
```

Note that JPype behaves correctly (and doesn't error) when you omit the "int x" argument to the methods.
This is with JPype 0.6.3 and py36_0.

**Comment by Thrameos** [comment] 2018-09-21 18:32
Hmm.  I will have to investigate this.  The argument matcher should try all combinations of the overloads independently thus if any matches it should have produced a correct match.  As there are two overloads both should have been checked.  I guess the correct way to debug would be to use the match report function but I have not tested that recently.

**Comment by Thrameos** [comment] 2018-09-21 18:42
Actually I think there may be a misinterpretation.  It didn't say it can't find 'bar', it said it can't find '[init'.  Thus the problem is with the constructor and not the varargs.  But rerunning it does show a problem with the current master version.

```
noargs
Java says:
..but JPype errors:
Traceback (most recent call last):
  File "Foo.py", line 8, in <module>
    foo().bar(1)
RuntimeError: Ambiguous overloads found: (LFoo;I) vs (LFoo;I[Ljava/lang/String;)
        at unknown(native\common\jp_method.cpp:124)
```

It did not consider the `int` to be an exact match so it tagged that an empty list could be a possiblity.  Forcing the issue by casting the python int to a java int corrects the issue.

```
foo().bar(jpype.JInt(1))
              ^^^^^^^  Casting forces bar(int) to match better than bar(int, String...)
```

I am currently taking a break from the project due to a departing employee at my work, but I will leave this request open and test it with the current development branch when I return.

**Comment by knabbers** [comment] 2018-09-23 01:27
Sorry about that - I pasted the wrong error. I had meant to paste the `RuntimeError: Ambiguous overloads found` one. (though when I was playing around I noticed that you get `RuntimeError: No matching overloads found for [init` when a constructor isn't defined in the Java class)

**Comment by Thrameos** [comment] 2018-09-25 15:49
Does the exact match method work for you? I can try to give preference something that matches all over matches all and an empty list but there will always be edge cases as we only have 4 matching levels.  Those being exact, implicit, explicit, none.  As both the overloads were implicit, (python long to java int, and empty to null list) they are being tagged as implicit and thus triggering ambiguous warning.  To break this implicit axact arguments would need to be given preference over implicit various args.  I wonder if the Java binding rules would help.

**Comment by Thrameos** [comment] 2018-10-15 20:02
I am going to tag this one to be fixed when I port over the C++ method resolving code to java.  It isn't too hard to check to see if a method takes the same type arguments as another through is assignable ignoring the extra vargs argument and placing it into the precedence list.  But the current C++ logic for it would take some time add.  Once I finish the porting, performing the check will be pretty trivial.  Thus I will leave this open until that time.

**Comment by AIDnanjing0829** [comment] 2019-04-09 01:18
I want to know this problem that RuntimeError: No matching overloads found for [init in find. at native\common\jp_method.cpp:127 ,has been solved?

**Comment by Thrameos** [comment] 2019-05-22 15:45
Not sure.  Need to run a test on the new master.  It was addressed, but we do not have  test for it yet.

**Comment by AIDnanjing0829** [comment] 2019-05-22 15:54
My python's environment is python3.7

**Closed** 2020-02-29 05:49 UTC
Labels: bug
