### ISSUE TITLE
JPype does not have ``getPeerCertificates()`` in the code base nor does the word ``Peer`` appear anywhere.  JPype is a library that allows Python to call Java methods.   The user code makes the call, we just are routing it.   I also checked in JayDeBeAPI and the word "Peer" never appears in that codebase.  Thus the error is likely in the user code base not the libraries.

### ISSUE THREAD

**Issue by bb14742** [jpype-project/jpype#990] opened 2021-06-25 18:36 UTC
JPype does not have ``getPeerCertificates()`` in the code base nor does the word ``Peer`` appear anywhere.  JPype is a library that allows Python to call Java methods.   The user code makes the call, we just are routing it.   I also checked in JayDeBeAPI and the word "Peer" never appears in that codebase.  Thus the error is likely in the user code base not the libraries.

I suggest reviewing the stack trace on the error to locate who made the call and updating it appropriately.

_Originally posted by @Thrameos in https://github.com/jpype-project/jpype/issues/988#issuecomment-867881972_

This issue is a continuation of https://github.com/jpype-project/jpype/issues/988, which was closed by Thrameos. I have a Python program that calls the JayDeBeApi module, which relies on JPype1. In the 988 issue Thrameos states “JPype does not have getPeerCertificates() in the code base nor does the word Peer appear anywhere.”. Thrameos also states, “I also checked in JayDeBeAPI and the word "Peer" never appears in that codebase. Thus the error is likely in the user code base not the libraries.”.
I understand that neither JayDeBeApi nor JPype1 makes a direct call to getPeerCertificatesChain(). My example Python program, which connects to HANA does not make a call to getPeerCertificatesChain(). However, JPype1 is referencing a Java method, which calls another method and so on which eventually calls getPeerCertificatesChain(). I am not sure what changes are required to have the Java code reference getPeerCertificates() instead of getPeerCertificatesChain().  Perhaps JPype1 needs to support Java 15 since getPeerCertificatesChain() is not part of Java 15. 
Here is the stack track which contains the getPeerCertificatesChain() error:
File "org.jpype.JPypeContext.java", line -1, in org.jpype.JPypeContext.callMethod
  File "Method.java", line 564, in java.lang.reflect.Method.invoke
  File "DelegatingMethodAccessorImpl.java", line 43, in jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke
  File "NativeMethodAccessorImpl.java", line 64, in jdk.internal.reflect.NativeMethodAccessorImpl.invoke
  File "NativeMethodAccessorImpl.java", line -2, in jdk.internal.reflect.NativeMethodAccessorImpl.invoke0
  File "DriverManager.java", line 228, in java.sql.DriverManager.getConnection
  File "DriverManager.java", line 677, in java.sql.DriverManager.getConnection
  File "DriverSapDB.java", line 1318, in com.sap.db.jdbc.DriverSapDB.connect
  File "DriverSapDB.java", line 1662, in com.sap.db.jdbc.DriverSapDB._connect
  File "ConnectionSapDB.java", line 2204, in com.sap.db.jdbc.ConnectionSapDB._connectAnchor
  File "Session.java", line 116, in com.sap.db.jdbc.Session.newInstance
  File "SecureSession.java", line 37, in com.sap.db.jdbc.SecureSession$1.newInstance
  File "SecureSession.java", line 97, in com.sap.db.jdbc.SecureSession.<init>
  File "SecureSession.java", line 258, in com.sap.db.jdbc.SecureSession._finishSSLInit
  File "SSLSession.java", line 295, in javax.net.ssl.SSLSession.getPeerCertificateChain
Exception: Java Exception

**Comment by Thrameos** [comment] 2021-06-25 21:41
Please note that you can reply to a close issue.   Closing the issue just removes the issue from the list of active items for the project.   Simply because it is closed does not mean it won't get a response.

---------


Base on the stack trace I can identify the issue.  There is a lot to digest here so let me break it down.  Please note that Python and Java have opposite orders for presenting stack traces.   Python places the entry point at the bottom, while Java places it at the top.   Hence it may have caused some confusion as JPype is farthest from the error, and not the nearest to as it would be in a Python stack trace.

The originating request was "DatabaseManager.getConnection()"  which is the typical way to open a connect (likely the call that was issues by JayDeeBeeAPI. )     So the python command was likely ``cxt = db.connect()``.

That ``DatabaseManager.getConnection`` call is of type "caller sensitive".  A caller sensitive method must be called from within Java and never called externally though JNI as it must have a Security context to see if it is a privileged access.  JNI has a null security context which would cause the call to fail.   Therefore, to give it a valid context JPype redirected the call to an internal proxy which rewrote the Security context to "org.jpype" as seen in ``File "org.jpype.JPypeContext.java", line -1, in org.jpype.JPypeContext.callMethod``.  JPype has no idea what is being called, it is just lending it credentials so the call is not rejected outright.   The next section is just redirects through the Method reflection as we have a methodId and an argument list we are trying to redirect without executing it through compiled code.   Again nothing to do with the call.  This is just routine routing.   So everything about JPype and reflection is a red herring as it was extra layers needed to work around the structure of JNI and security contexts.

Thus we can ignore all the routing which gets us to the call that initiated the error.

```
File "DriverManager.java", line 228, in java.sql.DriverManager.getConnection
File "DriverManager.java", line 677, in java.sql.DriverManager.getConnection
```

This arrives as the "DriverManager" which is actually doing the work.   It takes the string argument and looks up what driver is being requested.   It determined that "com.sap.db.jdbc.DriverSapDB" is the requested driver.  It created and instance and then call the initialization routine.  

As DriverManager is just a front end it is again just more routing.   So that user was actually just calling with ``cxt=db.connect()`` was

```
File "DriverSapDB.java", line 1318, in com.sap.db.jdbc.DriverSapDB.connect
```

During the process of servicing the connect it executes...

```
File "SecureSession.java", line 97, in com.sap.db.jdbc.SecureSession.
File "SecureSession.java", line 258, in com.sap.db.jdbc.SecureSession._finishSSLInit
File "SSLSession.java", line 295, in javax.net.ssl.SSLSession.getPeerCertificateChain
Exception: Java Exception
```

Thus you will need to contact SAP driver vendor which is as far as I can tell proprietary code.  The problem is in their driver.  https://www.sap.com/index.html

As this isn't relevant to JPype, I will close this issue.  I can't close tickets on JayDeBeAPI but I suggest closing that as well as it isn't relevant to that project either.

**Closed by Thrameos** 2021-06-25 21:41 UTC

**Comment by bb14742** [comment] 2021-06-28 20:44
Thrameos: Updating the HANA database driver (ngdbc.jar) appears to have resolved the issue with JPype1 and Java 15. My co-worker who experienced this issue still receives a "Not Authorized" issue, but I believe this is a database permission error, which we are working to resolve. He no longer receives the getPeerCertificates() or getPeerCertificatesChain() error. Thank you for the detailed explanation.

**Comment by Thrameos** [comment] 2021-06-28 21:02
No problem.  Depending on what you are doing you may want to look at jpype.dbapi2 or Apache arrow.   JayDeBeAPI is an older API which is a front end for both CPython and Jython.   jpype.dbapi2 is a replacement dedicated to CPython which is about twice as fast.   Apache Arrow is a direct columnwise transfer method which is considerably faster.

See for further discussion...

https://uwekorn.com/2020/12/30/fast-jdbc-revisited.html
